<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Abstractions/Services/" />
    <Folder Include="Enums/" />
    <Folder Include="Models/" />
    <Folder Include="Models/Builders/" />
    <Folder Include="Utils/" />
  </ItemGroup>

</Project>
